import type { NextPage } from "next";
import Head from "next/head";
import styles from "@styles/Home.module.css";
import React from "react";
import Banner from "@components/Banner";
import ProgramList from "@components/ProgramList";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>FollowMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />

      <main className={styles.main}>
        <h1 className={styles.title}>FOLLOWME</h1>
        <ProgramList />
      </main>
    </div>
  );
};

export default Home;
